### ISSUE TITLE
Can you update the README to include details on how to get the data?

### ISSUE THREAD

**Issue by ffund** [AliaaMahgoub/sound-scenes#1]
Can you update the README to include details on how to get the data? Is the data available publicly?

Thanks! (I really enjoyed your presentation at the ARISE colloquium.)

**Comment by AliaaMahgoub** [comment]
Thank you for your feedback!

The data is publicly available, I used the [TAU Urban Acoustic Scenes 2019, Development dataset](https://zenodo.org/record/2589280#.YTV3EZ1Kg2y).

**Comment by ffund** [comment]
Thanks!
